### ISSUE TITLE
Не импортируются исходные данные

### ISSUE THREAD

**Issue by plazmer** [SPLYUSHKA/SG_Test#1]
1. Наблюдается взаимная блокировка на основании наших исходных данных - для импорта подразделений требуется сотрудник, для импорта сотрудников требуется подразделение. Лучшим вариантом было бы null в качестве руководителя подразделения, если его не удаётся найти и warning при импорте данных. Повторный импорт после завершения импорта сотрудников должен будет обновить руководителей подразделений.
2. Неправильно обрабатывается поиск подразделения с родительским, в итоге импортируется только главный офис
3. Trim() позволит дополнительно очистить данные от пробелов
4. Дамп данных .sql на самом деле импортируется только с помощью pg_restore

**Comment by SPLYUSHKA** [comment]
Здравствуйте!
По замечаниям могу дать ответ:
1. Не указано в требованиях, как следует осуществлять добавление записей об отделах. При первоначальном использовании файлов, где не указанны руководили все работает и позволяет в дальнейшем руководителей обновить. При необходимости легко можно внести исправления в код и сделать добавление null
2. Все корректно импортируется, если сперва добавить из файла без руководителей. Опять же можно внести изменение (пункт 1) используя после этого файл с руководителями.
3. Вызовы Trim имеются в опциях Split, пробелы внутри удаляются с помощью регулярного выражения
4. В задании не указано, в каком виде нужен файл для восстановления
Если есть возможность , то могу внести изменения в код
